### ISSUE TITLE
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'

### ISSUE THREAD

**Issue by suavelad** [sivulich/mqttasgi#5] opened 2022-02-05 12:36 UTC
I am getting this error when running this command:

mqttasgi -H test.mosquitto.org -p 1883 iot_logger.asgi:application

File "/Users/xxxx/Documents/Projects/proj_test/proj/env/lib/python3.9/site-packages/mqttasgi/server.py", line 331, in create_application
    self.application_data[app_id]['instance'] = application(scope)
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'

**Comment by sivulich** [comment] 2022-02-05 12:40
Hi Suavelad,

That error is caused by using a Django 3.X version, you should downgrade to Django 2.X

We are currently working on the support for Django 3.X, now it supports asgi out of the box so we have to adapt the whole application and consumer interaction.

thanks for reporting your issue.

**Comment by suavelad** [comment] 2022-02-05 20:32
Thank you for the update

**Comment by suavelad** [comment] 2022-02-05 21:17
I just tried it but I get the error below when using Django 2.2.27

from django.core.asgi import get_asgi_application
ModuleNotFoundError: No module named 'django.core.asgi'

**Comment by sivulich** [comment] 2022-02-07 12:47
Django incorporated asgi to its core in django 3.x.

To get the asgi application on your `asgi.py`:
```python
import os
import django
from channels.routing import get_default_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "my_project.settings")
django.setup()
application = get_default_application()
```

**Comment by sivulich** [comment] 2022-02-09 13:57
Closing this issue as it was a problem with the Django version and is being addressed in this [issue](https://github.com/sivulich/mqttasgi/issues/2)

**Closed by sivulich** 2022-02-09 13:57 UTC
